version: '3'

services:
  app:
    build: .
    # image: bk_cypress:latest
    network_mode: "host"
    environment: 
      - BUILDKITE_BUILD_CHECKOUT_PATH=.
      - BUILDKITE_BUILD_ID=${BUILDKITE_BUILD_ID}
      - BUILDKITE_PIPELINE_NAME=${BUILDKITE_PIPELINE_NAME}
      - BUILDKITE_LABEL=${BUILDKITE_LABEL}
      - BUILDKITE_BRANCH=${BUILDKITE_BRANCH}
      - BUILDKITE_COMMIT=${BUILDKITE_COMMIT}
      - BUILDKITE_PULL_REQUEST=${BUILDKITE_PULL_REQUEST}
      - BUILDKITE=${BUILDKITE}
      - BUILDKITE_PARALLEL_JOB_COUNT=${BUILDKITE_PARALLEL_JOB_COUNT}
      - BUILDKITE_PARALLEL_JOB=${BUILDKITE_PARALLEL_JOB}
      - REDEFINE_SESSION_ID=${REDEFINE_SESSION_ID}
      - REDEFINE_AUTH=${REDEFINE_AUTH}
    entrypoint: ["/bin/bash","-c", "chmod +x /app/redefine/entrypoint.sh && /app/redefine/entrypoint.sh"]
