#!/bin/bash

# echo "--- Node version"
# node --version

# echo "--- NPM version"
# npm --version

# echo "--- Cypress version"
# npx cypress --version

# echo "--- Env vars"
# chmod 777 scripts/read_envs.sh
# scripts/read_envs.sh

# echo "--- Installing npm packages"
# npm install --save-dev
# npm install

npm install cypress@10.10

pip3 install -U redefine --index-url https://redefine.dev/pip/
export REDEFINE_SESSION_ID=$(cat redefine/session_id.txt)
redefine config set stable_branch=master
redefine start --verbose --cypress --worker

# script.js takes specs.txt file which is generated by redefine
# uses BUILDKITE_PARALLEL_JOB, and BUILDKITE_PARALLEL_JOB_COUNT
# and prints the list of spec files to run in this specific worker
output=$(node /app/script.js)

# run cypress with the spec files for the current worker 
npm start & npx cypress run --spec ${output}





