env:
  TERM: "xterm"
  REDEFINE_SESSION_ID: 12345678-4060-4636-9fb6-49161e687098684789
  REDEFINE_AUTH: f94c1797-9fc9-49c8-9436-be609843a320::1382f531-acdc-4775-a85e-7a01f242c679

steps:
  - label: "run cypress in dry run"
    command: | 
      mkdir -p /tmp/redefine
      mkdir -p redefine
      rm -f $BUILDKITE_BUILD_CHECKOUT_PATH/effective_config.yml
      npm install
      pip uninstall -y redefine
      pip install -U redefine --index-url https://redefine.dev/pip
      # redefine config set environment=staging
      # redefine config set redefine_address=dune-tf-staging.redefine.dev
      redefine config set stable_branch=master
      redefine config set selection_method=2
      redefine config set time_limit=100
      rm -f /tmp/redefine/redefine_specs.txt
      redefine start --verbose --cypress --active --dry-run --output-path=/tmp/redefine/redefine_specs.txt
      export REDEFINE_DEBUG_MODE=True
      date && npx cypress run --env REDEFINE_DEBUG_MODE=True && date
      # redefine stop
      cat /tmp/redefine/
      cat /tmp/redefine/redefine_specs.txt
      cp /tmp/redefine/redefine_specs.txt redefine/redefine_specs.txt

    artifact_paths:
      - redefine/redefine_specs.txt
  - wait



  - label: ":docker: docker tests"
    parallelism: 3
    plugins:
      - docker-compose#v3.7.0:
          run: app
          volumes:
            - "./redefine:/app/redefine"
          propagate-environment: true
