env:
  TERM: "xterm"
  REDEFINE_AUTH: e88afb65-65ef-4798-bc9d-db4c5342f7f3::163bf879-4060-4636-9fb6-49161e68095a
  REDEFINE_SESSION_ID: 00000000-4060-4636-9fb6-49161e68095a


steps:
  - label: ":dolphin: Redefine verify"
    command: |
        redefine config set stable_branch=master
        redefine verify --cypress
    env:
        REDEFINE_SESSION_ID: 00000000-4060-4636-9fb6-49161e68095a
        REDEFINE_AUTH: e88afb65-65ef-4798-bc9d-db4c5342f7f3::163bf879-4060-4636-9fb6-49161e68095a

  - label: "run cypress in dry run"
    command: | 
      pip install -U redefine --index-url https://redefine.dev/pip/
      redefine config set stable_branch=master
      redefine config set dry_run=true
      redefine start --discover --cypress
      mkdir -p redefine
      date && npx cypress run 1> redefine/specs.txt && date
    env:
        REDEFINE_SESSION_ID: 00000000-4060-4636-9fb6-49161e68095a
        REDEFINE_AUTH: e88afb65-65ef-4798-bc9d-db4c5342f7f3::163bf879-4060-4636-9fb6-49161e68095a
    artifact_paths:
      - "redefine/specs.txt"
  - wait

  - label: ":docker: docker tests"
    parallelism: 3
    plugins:
      - artifacts#v1.9.0:
          download: "redefine/specs.txt"
      - docker-compose#v3.7.0:
          run: app
          volumes:
            - "./redefine:/app/redefine"
          propagate-environment: true
