env:
  TERM: "xterm"
  REDEFINE_AUTH: e88afb65-65ef-4798-bc9d-db4c5342f7f3::163bf879-4060-4636-9fb6-49161e68095a
  REDEFINE_SESSION_ID: 00000000-4060-4636-9fb6-49161e68095a


steps:

  - label: ":docker: run cypress in docker"
    env:
      REDEFINE_AUTH: $$YOUR-REDEFINE-AUTH$$
    parallelism: 3
    plugins:
      - artifacts#v1.9.0:
          # Download redefine build artifacts from the previous step
          download: "redefine/*"
      - docker-compose#v3.7.0:
          run: app
          volumes:
            # Map redefine build artifacts to the docker container
            - "./redefine:/app/redefine"
          propagate-environment: true

