env:
  TERM: "xterm"
  REDEFINE_AUTH: e88afb65-65ef-4798-bc9d-db4c5342f7f3::163bf879-4060-4636-9fb6-49161e68095a
  REDEFINE_SESSION_ID: 00000000-4060-4636-9fb6-49161e68095a


steps:

  - label: "Redefine verify"
    env:
      REDEFINE_AUTH: $$YOUR-REDEFINE-AUTH$$
    command: |
        # Install redefine cli
        pip install -U redefine --index-url https://redefine.dev/pip/

        # Configure Redefine
        redefine config set stable_branch=main

        # Run redefine verify
        redefine verify --cypress

  - label: "run cypress in dry run"
    env:
      REDEFINE_AUTH: $$YOUR-REDEFINE-AUTH$$
    command: | 

    # Install redefine cli
      pip install -U redefine --index-url https://redefine.dev/pip/
      
    # Create a folder for redefine build artifacts to pass to the workers
      mkdir redefine

    # Generate redefine session_id
      export REDEFINE_SESSION_ID=$(redefine get session_id)
      echo $REDEFINE_SESSION_ID > redefine/session_id.txt

     # Configure redefine 
      redefine config set stable_branch=main
      redefine config set dry_run=true
      redefine start --discover --cypress
      
    # Run cypress in dry run mode
      npx cypress run 1> redefine/specs.txt

    artifact_paths:
      # upload redefine artifacts 
      - "redefine/*"
  - wait

  - label: ":docker: run cypress in docker with redefine"
    env:
      REDEFINE_AUTH: $$YOUR-REDEFINE-AUTH$$
    parallelism: 3
    plugins:
      - artifacts#v1.9.0:
          # Download redefine build artifacts from the previous step
          download: "redefine/*"
      - docker-compose#v3.7.0:
          run: app
          volumes:
            # Map redefine build artifacts to the docker container
            - "./redefine:/app/redefine"
          propagate-environment: true

