env:
  TERM: "xterm"
  REDEFINE_SESSION_ID: 00000000-4060-4636-9fb6-49161e68095a
  # REDEFINE_AUTH: 691b03c7-ad0d-4844-933c-f63b1ae5535f::7f16a346-3f0d-4bec-981b-20d9006fe0ba
  REDEFINE_AUTH: "e88afb65-65ef-4798-bc9d-db4c5342f7f3::163bf879-4060-4636-9fb6-49161e68095a"
  REDEFINE_ENVIRONMENT: "staging"

steps:
  # - label: ":dolphin: Redefine verify"
  #   command: |
  #     redefine config set stable_branch=master
        # redefine verify --cypress
  - label: "run cypress in dry run"
    command: | 
      mkdir -p /tmp/redefine
      mkdir -p redefine
      rm -f $BUILDKITE_BUILD_CHECKOUT_PATH/effective_config.yml
      npm install
      pip uninstall -y redefine
      pip install redefine --index-url https://redefine.dev/staging/pip/
      redefine config set environment=staging
      redefine config set redefine_address=dune-tf-staging.redefine.dev
      redefine config set stable_branch=master
      redefine config set dry_run=true
      redefine config set log_to_file=true
      # need to run redefine after setting config
      redefine start --prioritize --cypress --verbose --dry-run --output-path=/tmp/redefine/redefine_specs.txt
      export REDEFINE_DEBUG_MODE=True
      # use date to check how long it takes to run the dry run
      date && npx cypress run --env REDEFINE_DEBUG_MODE=True && date
      cat /tmp/redefine/redefine_specs.txt
      cp /tmp/redefine/redefine_specs.txt redefine/redefine_specs.txt

    artifact_paths:
      - redefine/redefine_specs.txt
  - wait



  - label: ":docker: docker tests"
    parallelism: 3
    plugins:
    plugins:
      - artifacts#v1.9.0:
          download: redefine/redefine_specs.txt
      - docker-compose#v3.7.0:
          run: app
          volumes:
            - "./redefine:/app/redefine"
          propagate-environment: true
