env:
  TERM: "xterm"
  REDEFINE_AUTH: e88afb65-65ef-4798-bc9d-db4c5342f7f3::163bf879-4060-4636-9fb6-49161e68095a
  REDEFINE_SESSION_ID: 00000000-4060-4636-9fb6-49161e68095a

steps:
  - label: "foo"
    command: | 
      cat > 1.txt << EOF
      cypress/e2e/1-getting-started/todo.cy.js
      cypress/e2e/2-advanced-examples/actions.cy.js
      cypress/e2e/2-advanced-examples/aliasing.cy.js
      cypress/e2e/2-advanced-examples/assertions.cy.js
      cypress/e2e/2-advanced-examples/connectors.cy.js
      cypress/e2e/2-advanced-examples/cookies.cy.js
      cypress/e2e/2-advanced-examples/cypress_api.cy.js
      cypress/e2e/2-advanced-examples/files.cy.js
      cypress/e2e/2-advanced-examples/location.cy.js
      cypress/e2e/2-advanced-examples/misc.cy.js
      cypress/e2e/2-advanced-examples/navigation.cy.js
      cypress/e2e/2-advanced-examples/network_requests.cy.js
      cypress/e2e/2-advanced-examples/querying.cy.js
      cypress/e2e/2-advanced-examples/spies_stubs_clocks.cy.js
      cypress/e2e/2-advanced-examples/storage.cy.js
      cypress/e2e/2-advanced-examples/traversal.cy.js
      cypress/e2e/2-advanced-examples/utilities.cy.js
      cypress/e2e/2-advanced-examples/viewport.cy.js
      cypress/e2e/2-advanced-examples/waiting.cy.js
      cypress/e2e/2-advanced-examples/window.cy.js
      EOF
      mkdir -p redefine
      cp 1.txt redefine
      cat redefine/1.txt
    artifact_paths:
      - "1.txt"
  - wait
  - label: ":docker: docker tests"
    parallelism: 3
    plugins:
      - docker-compose#v3.7.0:
          run: app
          volumes:
            - "./redefine:/app"
          propagate-environment: true
          
